- name: AI
  expand-mobile-page-navigation: true
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: OpenAI
              collapse-after: 10
              feeds:
                - url: "https://openai.com/news/rss.xml"
        - type: rss
          title: DeepMind
          collapse-after: 10
          feeds:
            - url: "https://deepmind.google/blog/rss.xml"
        - type: rss
          title: Google Researcn Blog
          collapse-after: 10
          feeds:
            - url: "https://feeds.feedburner.com/blogspot/gJZg"