- name: Backend
  expand-mobile-page-navigation: true
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: 週間Railsウォッチ
              collapse-after: 10
              feeds:
                - url: "https://techracho.bpsinc.jp/rss"
            - type: rss
              title: Ruby Weekly
              collapse-after: 10
              feeds:
                - url: "https://cprss.s3.amazonaws.com/rubyweekly.com.xml"