- name: Database
  expand-mobile-page-navigation: true
  columns:
    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: AWS Database Blog
              collapse-after: 10
              feeds:
                - url: "https://aws.amazon.com/jp/blogs/database/feed/"
    - size: full
      widgets:
        - type: bookmarks
          groups:
            - links:
                - title: 実践データベース設計
                  url: "https://speakerdeck.com/recruitengineers/shi-jian-detabesushe-ji"